[package]
name = "rust-protodanksharding-example"
version = "0.1.0"
edition = "2021"

[dependencies]
blstrs = "0.6.1"
ff = "0.12.0"
group = "0.12"
pairing_lib = { version = "0.22", package = "pairing" }

[dev-dependencies]
rand = "0.8.3"
